---
# tasks file for logrotate

- name: Configure logrotate
  package:
    name: logrotate
    state: present
  when: logrotate_scripts is defined and logrotate_scripts|length > 0

- name: Setup logrotate.d scripts
  template:
    src: "{{ logrotate_config_file }}.j2"
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
    owner: "{{ logrotate_user }}"
    group: "{{ logrotate_group }}"
    mode: 0644
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined

- name: ensure logrotate is in /etc/cron.hourly
  file:
    src: /etc/cron.daily/logrotate
    dest: /etc/cron.hourly/logrotate
    state: link
    force: yes
    mode: 0755 # the file needs to be excutable